// SIGN UP
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_ERROR = "SIGNUP_ERROR";

// SIGN IN
const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
const SIGNIN_ERROR = "SIGNIN_ERROR";

// SIGN OUT
const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
const SIGNOUT_ERROR = "SIGNOUT_ERROR";

// RESET PASSWORD
const RESET_SUCCESS = "RESET_SUCCESS";
const RESET_ERROR = "RESET_ERROR";

export {SIGNUP_SUCCESS, SIGNUP_ERROR,
    SIGNIN_SUCCESS, SIGNIN_ERROR,
    SIGNOUT_SUCCESS, SIGNOUT_ERROR,
    RESET_SUCCESS, RESET_ERROR,
};